from Simulation_Frame import Simulation
from Solutions import DirectMatching,YouSupplyAlgo,OptimizedDirectMatching,GeneticAlgorithm,MultiSinkDirectMatching

open("metrics.txt","w").close()

sim = Simulation(area=10000,size=1000,range=20,items = ["1","2","3","4","5","6","7","8","9","10"])
sim.populate_nodes()
all_nodes = sim.get_nodes().copy()
# print(sim)

# sol = MultiSinkDirectMatching(sim,name="MultiSinkDM")
# paths = sol.solve()
# sol.print_paths()
# tot_dist = sol.get_total_distance()
# print(f"Total Distance of all Paths with DirectMatching: {tot_dist}")
# sol.get_satisfaction_metrics()
# sol.get_all_metrics(out="metrics.txt")
# sol.csv_metrics()

# sol = OptimizedDirectMatching(sim,name="Optimized Direct Matching")
# paths = sol.solve()
# sol.print_paths()
# tot_dist = sol.get_total_distance()
# print(f"Total Distance of all Paths with Optimized DirectMatching: {tot_dist}")
# sol.get_satisfaction_metrics()
# sol.get_all_metrics(out="metrics.txt",name="Optimized Direct Matching")
# sol.csv_metrics()


# sim.load_nodes(all_nodes)
# sol = YouSupplyAlgo(sim,geo_size=50)
# sol.solve(show=False)
# sol.print_paths()
# tot_dist = sol.get_total_distance()
# print(f"Total Distance of all Paths with YouSupply: {tot_dist}")
# sol.get_satisfaction_metrics()
# sol.get_all_metrics(out="metrics.txt")
# unsatisfied_nodes = sol.get_unsatisfied_nodes()
# sol.csv_metrics()
# # sol.plotallpaths()


sim.load_nodes(all_nodes)
sol = GeneticAlgorithm(simulation=sim)
paths = sol.solve()
sol.print_paths()
tot_dist = sol.get_total_distance()
print(f"Total Distance of all Paths with Genetic Algorithm: {tot_dist}")
sol.get_satisfaction_metrics()
sol.get_all_metrics(out="metrics.txt",name="Genetic Algorithm")
unsatisfied_nodes = sol.get_unsatisfied_nodes()
sol.csv_metrics()

sim.load_nodes(unsatisfied_nodes)
sol = MultiSinkDirectMatching(sim,name="MSDM + GA")
paths = sol.solve()
sol.print_paths()
tot_dist = sol.get_total_distance()
print(f"Total Distance of all Paths with MSDD after YouSupply: {tot_dist}")
sol.get_satisfaction_metrics()
sol.get_all_metrics(out="metrics.txt",name="Direct Matching after YouSupply")
sol.csv_metrics()